postgres_db:
  image: postgres:9.5.0

web:
  build: .
  command: rails server -b 0.0.0.0
  ports:
    - '80:3000'
    - '443:3000'
  links:
    - postgres_db
  environment:
    - SECRET_KEY_BASE
    - MEMETICAME_FCM_KEY
    - MEMETICAME_EMOTIONS_PREVIEW_KEY
    - MEMETICAME_DROPBOX_ACCESS_TOKEN
    - MEMETICAME_DROPBOX_USER_ID
    - RAILS_SERVE_STATIC_FILES=true
    - RAILS_LOG_TO_STDOUT=true
  volumes:
    - ./volumes/memeticame:/usr/src/app/public/system
  restart: always
